apiVersion: apps/v1
kind: Deployment
metadata:
  name:  eduze-dev:1.1
  namespace: default
  labels:
    app:  eduze-dev:1.1
spec:
  selector:
    matchLabels:
      app: eduze-dev:1.1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  eduze-dev:1.1
    spec:
      containers:
      - name:  eduze-dev:1.1
        image:  eduze-dev:1.1:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: eduze-dev:1.1
              key: DB_HOST
        ports:
        - containerPort:  80
          name:  eduze-dev:1.1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always